#!/usr/bin/env bash
# Golden regression for the rendered tree, plus the safety assertions that no
# unit test can make because they are about generated bytes rather than about
# a function's return value.
#
# Two variants are rendered, because the backend is desired state and the
# `local` and `r2` choices produce different backend documents against the same
# colors.yml — and the R2 one is the path a real deployment takes.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
state="$root/test/fixtures/colors.yml"
goldens="$root/test/resources/golden"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
accept=0
[ "${1:-}" = --accept ] && accept=1

build() {
  local variant=$1
  shift
  (cd "$root" && env POSTGRES_HA_LIB_ROOT="$root" COLORS_PAR_WORKDIR="$tmp/$variant" \
    "$@" ./green build -f "$state" >/dev/null)
  if [ "$accept" = 1 ]; then
    rm -rf "${goldens:?}/$variant"
    mkdir -p "$goldens/$variant"
    cp -r "$tmp/$variant/." "$goldens/$variant/"
    echo "  accepted — $variant"
  else
    diff -qr "$goldens/$variant" "$tmp/$variant"
    echo "  ok — $variant"
  fi
}

build local COLORS_PAR_PROVIDER_BACKEND=local
build r2

profile=postgres-ha-fixture
base="$tmp/r2/$profile"

for stage in postgres-ha-infrastructure postgres-ha-dns postgres-ha-ansible-local \
             postgres-ha-cluster postgres-ha-acceptance; do
  [ -d "$base/$stage" ] || { echo "golden: missing stage $stage" >&2; exit 1; }
done

# --- infrastructure ---------------------------------------------------------
infra="$base/postgres-ha-infrastructure/main.tf"
grep -q 'data "digitalocean_vpc" "default"' "$infra"
grep -q 'region = "ams3"' "$infra"
grep -q 'vpc_uuid = data.digitalocean_vpc.default.id' "$infra"
if grep -qE 'digitalocean_vpc" "(cluster|owned)"|ip_range *=' "$infra"; then
  echo 'golden: the deployment creates or describes a VPC instead of discovering one' >&2
  exit 1
fi
grep -q 'count    = length(local.node_names)' "$infra"
grep -q 'postgres-ha-fixture-1", "postgres-ha-fixture-2", "postgres-ha-fixture-3' "$infra"
grep -q 's-2vcpu-4gb' "$infra"
grep -q 'ubuntu-24-04-x64' "$infra"
[ "$(grep -c 'prevent_destroy = true' "$infra")" -ge 2 ] || {
  echo 'golden: infrastructure lost its destroy guard' >&2; exit 1
}
# Administrative and database ingress must never be open to the world, and
# everything the cluster says to itself must be VPC-scoped.
if grep -B2 'port_range       = "22"' "$infra" | grep -q '0.0.0.0/0'; then
  echo 'golden: SSH is open to the world' >&2; exit 1
fi
if grep -A1 'source_addresses = \[' "$infra" | grep -q '0.0.0.0/0'; then
  echo 'golden: an inbound rule admits the world' >&2; exit 1
fi
grep -q 'source_addresses = \[data.digitalocean_vpc.default.ip_range\]' "$infra"
for output in vpc_id vpc_ip_range node_public_ips node_private_ips; do
  grep -q "output \"$output\"" "$infra" || {
    echo "golden: infrastructure no longer publishes $output" >&2; exit 1
  }
done

# --- the client endpoint ----------------------------------------------------
dns="$base/postgres-ha-dns/main.tf"
[ "$(grep -c 'resource "cloudflare_dns_record"' "$dns")" -eq 3 ] || {
  echo 'golden: the endpoint no longer resolves to all three nodes' >&2; exit 1
}
[ "$(grep -c 'name    = "pg-ha.fixture.example"' "$dns")" -eq 3 ]
grep -q 'proxied = false' "$dns"
if grep -q 'proxied = true' "$dns"; then
  echo 'golden: a proxied record cannot carry the PostgreSQL wire protocol' >&2; exit 1
fi

# --- remote state -----------------------------------------------------------
grep -q "$profile/postgres-ha-infrastructure.tfstate" \
  "$base/postgres-ha-infrastructure/backend.tf.json"
grep -q "$profile/postgres-ha-dns.tfstate" "$base/postgres-ha-dns/backend.tf.json"
grep -q '"local"' "$tmp/local/$profile/postgres-ha-infrastructure/backend.tf.json"

# --- the cluster ------------------------------------------------------------
cluster="$base/postgres-ha-cluster"
patroni="$cluster/templates/patroni.yml.j2"
grep -q 'synchronous_mode: true' "$patroni"
grep -q 'synchronous_node_count: 1' "$patroni"
grep -q 'use_pg_rewind: true' "$patroni"
grep -q 'archive_mode: "on"' "$patroni"
grep -q 'archive_command: "pgbackrest --stanza=main archive-push %p"' "$patroni"
grep -q 'restore_command: "pgbackrest --stanza=main archive-get %f %p"' "$patroni"
grep -q 'data-checksums' "$patroni"
grep -q 'listen: {{ private_ip }}:5432' "$patroni"
if grep -qE 'listen: (0\.0\.0\.0|\*)' "$patroni"; then
  echo 'golden: PostgreSQL or the Patroni API is bound to a public interface' >&2
  exit 1
fi

etcd="$cluster/templates/etcd.conf.yml.j2"
grep -q 'initial-cluster: {% for host in' "$etcd"
grep -q 'listen-peer-urls: http://{{ private_ip }}:2380' "$etcd"
if grep -qE 'listen-(peer|client)-urls:.*0\.0\.0\.0' "$etcd"; then
  echo 'golden: etcd is listening on a public interface' >&2; exit 1
fi

haproxy="$cluster/templates/haproxy.cfg.j2"
grep -q 'option httpchk GET /primary' "$haproxy"
grep -q 'option httpchk GET /replica' "$haproxy"
grep -q 'bind {{ ansible_host }}:5432' "$haproxy"
grep -q 'bind 127.0.0.1:5433' "$haproxy"
grep -q 'on-marked-down shutdown-sessions' "$haproxy"

pgbackrest="$cluster/templates/pgbackrest.conf.j2"
grep -q 'repo1-type=s3' "$pgbackrest"
grep -q 'repo1-s3-endpoint=account.r2.cloudflarestorage.com' "$pgbackrest"
grep -q 'repo1-s3-uri-style=path' "$pgbackrest"
grep -q 'repo1-retention-full=4' "$pgbackrest"
grep -q 'repo1-path=/postgres-ha-fixture' "$pgbackrest"

# The verified restore must never be able to write into the shared repository.
check="$cluster/templates/postgres-ha-restore-check.j2"
grep -q -- '--archive-mode=off' "$check" || {
  echo 'golden: the verified restore could promote with archiving enabled and poison the repository' >&2
  exit 1
}
grep -q 'restore-check-max-lag\|MAX_LAG' "$check"
grep -q '/primary' "$cluster/templates/postgres-ha-backup.j2"
grep -q '/replica' "$check"

for unit in postgres-ha-heartbeat postgres-ha-backup postgres-ha-restore-check; do
  for suffix in '' .service .timer; do
    [ -f "$cluster/templates/$unit$suffix.j2" ] || {
      echo "golden: missing $unit$suffix.j2" >&2; exit 1
    }
  done
done
grep -q 'OnCalendar=\*-\*-\* 01:00:00' "$cluster/templates/postgres-ha-backup.timer.j2"
grep -q 'OnCalendar=\*-\*-\* 03:00:00' "$cluster/templates/postgres-ha-restore-check.timer.j2"

# --- credentials reach the host through the environment, never through a file
for par in COLORS_PAR_POSTGRES_ADMIN_PASSWORD COLORS_PAR_POSTGRES_REPLICATION_PASSWORD \
           COLORS_PAR_BACKUP_R2_ACCESS_KEY_ID COLORS_PAR_BACKUP_R2_SECRET_ACCESS_KEY; do
  grep -Rq "lookup('env', *'$par')" "$cluster/templates" || {
    echo "golden: $par is no longer looked up at play time" >&2; exit 1
  }
done
grep -q 'no_log: true' "$cluster/main.yml"

# --- acceptance asserts the four things this package exists to provide -------
acceptance="$base/postgres-ha-acceptance/acceptance.sh"
grep -q 'standbys are streaming from the primary' "$acceptance"
grep -q 'WAL archiving is continuous' "$acceptance"
grep -q 'the backup repository holds' "$acceptance"
grep -q 'the verified restore passed' "$acceptance"

# POSIX grep on purpose. rg is not declared in devenv.nix, and a missing binary
# inside `if` is simply false — the guard would pass silently on a machine
# without ripgrep, which is the one case it exists to cover.
if grep -rEq 'BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY|REPLACE_ME|github_pat_|ghp_|gho_|ghu_|ghs_|ghr_|AKIA[0-9A-Z]{16}' "$tmp"; then
  echo 'golden: credential-shaped material was rendered' >&2
  exit 1
fi

echo 'all postgres-ha goldens and safety assertions pass'
