#!/usr/bin/env bash
# Golden regression for the rendered trees, plus the safety assertions that no
# unit test can make because they are about generated bytes rather than about
# a function's return value.
#
# Two fixtures are rendered, because the SSH Keypair Standard has two modes and
# a package conforms only if both hold: `colors.yml` is keygen mode (no
# digitalocean-ssh-keys) and must declare the profile-named key resource and
# reference it by attribute; `optout.yml` supplies an explicit key id and must
# create nothing — its rendering is byte-for-byte what the package rendered
# before the standard, under its own profile. Each is rendered under both
# backends, because the backend is desired state and the `local` and `r2`
# choices produce different backend documents against the same colors.yml —
# and the R2 one is the path a real deployment takes.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
goldens="$root/test/resources/golden"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
accept=0
[ "${1:-}" = --accept ] && accept=1
status=0

build() {
  local fixture=$1 backend=$2
  local state="$root/test/fixtures/$fixture.yml"
  local profile
  profile=$(sed -n 's/^profile: //p' "$state")
  (cd "$root/green" && env POSTGRES_HA_LIB_ROOT="$root" COLORS_PAR_WORKDIR="$tmp/$backend-$fixture" \
    COLORS_PAR_PROVIDER_BACKEND="$backend" ./green build -f "$state" >/dev/null)
  local actual="$tmp/$backend-$fixture/$profile"
  local golden="$goldens/$backend/$profile"

  checks "$actual" "$profile" "$fixture" "$backend"

  if [ "$accept" = 1 ]; then
    rm -rf "${golden:?}"; mkdir -p "$golden"
    cp -r "$actual/." "$golden/"
    echo "  accepted — $backend/$profile"
  else
    [ -d "$golden" ] || { echo "golden missing for $backend/$profile; inspect build then run bb golden:accept" >&2; exit 1; }
    if diff -qr "$golden" "$actual"; then
      echo "  ok — $backend/$profile"
    else
      status=1
    fi
  fi
}

checks() {
  local base=$1 profile=$2 fixture=$3 backend=$4

  for stage in postgres-ha-infrastructure postgres-ha-dns postgres-ha-ansible-local \
               postgres-ha-cluster postgres-ha-acceptance; do
    [ -d "$base/$stage" ] || { echo "golden: $profile is missing stage $stage" >&2; exit 1; }
  done

  # --- infrastructure -------------------------------------------------------
  local infra="$base/postgres-ha-infrastructure/main.tf"
  grep -q 'data "digitalocean_vpc" "default"' "$infra"
  grep -q 'region = "ams3"' "$infra"
  grep -q 'vpc_uuid = data.digitalocean_vpc.default.id' "$infra"
  # An `ip_range` attribute is a VPC being described; the `vpc_ip_range` key of
  # the `params` output reports the discovered one and is not that.
  if grep -qE 'digitalocean_vpc" "(cluster|owned)"|^\s*ip_range *=' "$infra"; then
    echo "golden: $profile creates or describes a VPC instead of discovering one" >&2
    exit 1
  fi
  grep -q 'count    = length(local.node_names)' "$infra"
  grep -q 'postgres-ha-fixture-1", "postgres-ha-fixture-2", "postgres-ha-fixture-3' "$infra"
  grep -q 's-2vcpu-4gb' "$infra"
  grep -q 'ubuntu-24-04-x64' "$infra"
  [ "$(grep -c 'prevent_destroy = true' "$infra")" -ge 2 ] || {
    echo "golden: $profile: infrastructure lost its destroy guard" >&2; exit 1
  }
  # Administrative and database ingress must never be open to the world, and
  # everything the cluster says to itself must be VPC-scoped.
  if grep -B2 'port_range       = "22"' "$infra" | grep -q '0.0.0.0/0'; then
    echo "golden: $profile: SSH is open to the world" >&2; exit 1
  fi
  if grep -A1 'source_addresses = \[' "$infra" | grep -q '0.0.0.0/0'; then
    echo "golden: $profile: an inbound rule admits the world" >&2; exit 1
  fi
  grep -q 'source_addresses = \[data.digitalocean_vpc.default.ip_range\]' "$infra"
  for output in vpc_id vpc_ip_range node_public_ips node_private_ips params; do
    grep -q "output \"$output\"" "$infra" || {
      echo "golden: $profile: infrastructure no longer publishes $output" >&2; exit 1
    }
  done
  # The SSH Keypair Standard, both modes: keygen declares the profile-named key
  # resource and references it by attribute; opt-out keeps the literal list and
  # creates nothing.
  if [ "$fixture" = colors ]; then
    grep -q 'resource "digitalocean_ssh_key" "machine"' "$infra" || { echo "golden: $profile: keygen mode declares no key resource" >&2; exit 1; }
    grep -q 'ssh_keys       = \[digitalocean_ssh_key.machine.id\]' "$infra" || { echo "golden: $profile: keygen mode does not reference the key by attribute" >&2; exit 1; }
    grep -q 'ssh_key_id   = digitalocean_ssh_key.machine.id' "$infra" || { echo "golden: $profile: params carries no ssh_key_id" >&2; exit 1; }
    grep -q 'IdentityFile ~/.ssh/postgres-ha-fixture' "$base/postgres-ha-ansible-local/main.yml" || { echo "golden: $profile: the local stage names no identity file" >&2; exit 1; }
    grep -q '"ansible_ssh_private_key_file" : "/home/build-placeholder/.ssh/postgres-ha-fixture"' "$base/postgres-ha-cluster/inventory.json" || { echo "golden: $profile: the inventory does not name the generated key" >&2; exit 1; }
  else
    ! grep -q 'digitalocean_ssh_key' "$infra" || { echo "golden: $profile: opt-out mode must create no key" >&2; exit 1; }
    grep -qE '^\s+ssh_keys\s+= \["' "$infra" || { echo "golden: $profile: opt-out mode lost the literal key list" >&2; exit 1; }
    ! grep -qE '^\s+IdentityFile ' "$base/postgres-ha-ansible-local/main.yml" || { echo "golden: $profile: opt-out mode must not guess an identity file" >&2; exit 1; }
  fi

  # --- the client endpoint --------------------------------------------------
  local dns="$base/postgres-ha-dns/main.tf"
  [ "$(grep -c 'resource "cloudflare_dns_record"' "$dns")" -eq 3 ] || {
    echo "golden: $profile: the endpoint no longer resolves to all three nodes" >&2; exit 1
  }
  [ "$(grep -c 'name    = "pg-ha.fixture.example"' "$dns")" -eq 3 ]
  grep -q 'proxied = false' "$dns"
  if grep -q 'proxied = true' "$dns"; then
    echo "golden: $profile: a proxied record cannot carry the PostgreSQL wire protocol" >&2; exit 1
  fi

  # --- remote state ---------------------------------------------------------
  if [ "$backend" = r2 ]; then
    grep -q "$profile/postgres-ha-infrastructure.tfstate" "$base/postgres-ha-infrastructure/backend.tf.json"
    grep -q "$profile/postgres-ha-dns.tfstate" "$base/postgres-ha-dns/backend.tf.json"
  else
    grep -q '"local"' "$base/postgres-ha-infrastructure/backend.tf.json"
  fi

  # --- the cluster ----------------------------------------------------------
  local cluster="$base/postgres-ha-cluster"
  local patroni="$cluster/templates/patroni.yml.j2"
  grep -q 'synchronous_mode: true' "$patroni"
  grep -q 'synchronous_node_count: 1' "$patroni"
  grep -q 'use_pg_rewind: true' "$patroni"
  grep -q 'archive_mode: "on"' "$patroni"
  grep -q 'archive_command: "pgbackrest --stanza=main archive-push %p"' "$patroni"
  grep -q 'restore_command: "pgbackrest --stanza=main archive-get %f %p"' "$patroni"
  grep -q 'data-checksums' "$patroni"
  grep -q 'listen: {{ private_ip }}:5432' "$patroni"
  if grep -qE 'listen: (0\.0\.0\.0|\*)' "$patroni"; then
    echo "golden: $profile: PostgreSQL or the Patroni API is bound to a public interface" >&2
    exit 1
  fi

  local etcd="$cluster/templates/etcd.conf.yml.j2"
  grep -q 'initial-cluster: {% for host in' "$etcd"
  grep -q 'listen-peer-urls: http://{{ private_ip }}:2380' "$etcd"
  if grep -qE 'listen-(peer|client)-urls:.*0\.0\.0\.0' "$etcd"; then
    echo "golden: $profile: etcd is listening on a public interface" >&2; exit 1
  fi

  local haproxy="$cluster/templates/haproxy.cfg.j2"
  grep -q 'option httpchk GET /primary' "$haproxy"
  grep -q 'option httpchk GET /replica' "$haproxy"
  grep -q 'bind {{ ansible_host }}:5432' "$haproxy"
  grep -q 'bind 127.0.0.1:5433' "$haproxy"
  grep -q 'on-marked-down shutdown-sessions' "$haproxy"

  local pgbackrest="$cluster/templates/pgbackrest.conf.j2"
  grep -q 'repo1-type=s3' "$pgbackrest"
  grep -q 'repo1-s3-endpoint=account.r2.cloudflarestorage.com' "$pgbackrest"
  grep -q 'repo1-s3-uri-style=path' "$pgbackrest"
  grep -q 'repo1-retention-full=4' "$pgbackrest"
  grep -q 'repo1-path=/postgres-ha-fixture' "$pgbackrest"

  # The verified restore must never be able to write into the shared repository.
  local check="$cluster/templates/postgres-ha-restore-check.j2"
  grep -q -- '--archive-mode=off' "$check" || {
    echo "golden: $profile: the verified restore could promote with archiving enabled and poison the repository" >&2
    exit 1
  }
  grep -q 'restore-check-max-lag\|MAX_LAG' "$check"
  grep -q '/primary' "$cluster/templates/postgres-ha-backup.j2"
  grep -q '/replica' "$check"

  for unit in postgres-ha-heartbeat postgres-ha-backup postgres-ha-restore-check; do
    for suffix in '' .service .timer; do
      [ -f "$cluster/templates/$unit$suffix.j2" ] || {
        echo "golden: $profile: missing $unit$suffix.j2" >&2; exit 1
      }
    done
  done
  grep -q 'OnCalendar=\*-\*-\* 01:00:00' "$cluster/templates/postgres-ha-backup.timer.j2"
  grep -q 'OnCalendar=\*-\*-\* 03:00:00' "$cluster/templates/postgres-ha-restore-check.timer.j2"

  # --- credentials reach the host through the environment, never through a file
  for par in COLORS_PAR_POSTGRES_ADMIN_PASSWORD COLORS_PAR_POSTGRES_REPLICATION_PASSWORD \
             COLORS_PAR_BACKUP_R2_ACCESS_KEY_ID COLORS_PAR_BACKUP_R2_SECRET_ACCESS_KEY; do
    grep -Rq "lookup('env', *'$par')" "$cluster/templates" || {
      echo "golden: $profile: $par is no longer looked up at play time" >&2; exit 1
    }
  done
  grep -q 'no_log: true' "$cluster/main.yml"

  # The convergence gate has to speak Patroni's vocabulary, not an idea of it: a
  # healthy standby reports state `streaming`, and under synchronous mode one of
  # them reports role `sync_standby`. A gate that demands `running` from all three
  # fails on a perfectly healthy cluster and skips every task after it.
  grep -q 'healthy_states: \["running", "streaming"\]' "$cluster/main.yml"
  grep -q "selectattr('state', 'in', healthy_states)" "$cluster/main.yml"
  if grep -q "selectattr('state', 'equalto', 'running')" "$cluster/main.yml"; then
    echo "golden: $profile: the convergence gate demands running from every member again" >&2
    exit 1
  fi

  # --- acceptance asserts the four things this package exists to provide -----
  local acceptance="$base/postgres-ha-acceptance/acceptance.sh"
  grep -q 'standbys are streaming from the primary' "$acceptance"
  grep -q 'WAL archiving is continuous' "$acceptance"
  grep -q 'the backup repository holds' "$acceptance"
  grep -q 'the verified restore passed on' "$acceptance"
  # The endpoint resolves to every node including one that may be powered off,
  # which black-holes the SYN rather than refusing it. Acceptance must bound its
  # own wait, or the check meant to prove the endpoint survived a node loss is
  # the thing that hangs.
  grep -q 'connect_timeout=$CONNECT_TIMEOUT' "$acceptance"
  grep -q 'endpoint probes reached a read-write primary' "$acceptance"
  grep -q 'on_each_node' "$acceptance"
  grep -q 'last_archived_time > last_failed_time' "$acceptance"

  # POSIX grep on purpose. rg is not declared in devenv.nix, and a missing binary
  # inside `if` is simply false — the guard would pass silently on a machine
  # without ripgrep, which is the one case it exists to cover.
  if grep -rEq 'BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY|REPLACE_ME|github_pat_|ghp_|gho_|ghu_|ghs_|ghr_|AKIA[0-9A-Z]{16}' "$base"; then
    echo "golden: $profile: credential-shaped material was rendered" >&2
    exit 1
  fi
  # A Selmer tag that survived rendering is a typo or an unsupplied key.
  if grep -rn '<{' "$base"; then
    echo "golden: $profile left an unrendered Selmer tag" >&2; exit 1
  fi
  # A build that reached the real ~/.ssh would leak the operator's home into
  # committed bytes and make the goldens workstation-specific.
  if grep -rq "$HOME/.ssh" "$base"; then
    echo "golden: $profile rendered a real home directory; build must use the placeholder" >&2; exit 1
  fi
  # SSH Config Standard §6: the local stage takes addresses and the aliases as
  # Ansible extra-vars, never through Selmer, so its rendered playbook carries
  # no address at all.
  if grep -rEq '([0-9]{1,3}\.){3}[0-9]{1,3}' "$base/postgres-ha-ansible-local"; then
    echo "golden: $profile rendered an address into the local ssh_config stage" >&2; exit 1
  fi
}

for fixture in colors optout; do
  for backend in local r2; do
    build "$fixture" "$backend"
  done
done

[ "$status" = 0 ] && echo 'all postgres-ha goldens and safety assertions pass'
exit "$status"
